# Cloud Run Module Variables

variable "project_id" {
  description = "GCP Project ID"
  type        = string
}

variable "region" {
  description = "GCP Region for Cloud Run services"
  type        = string
}

variable "environment" {
  description = "Environment name (dev, staging, prod)"
  type        = string
}

# =============================================================================
# SCALING CONFIGURATION
# =============================================================================

variable "cloud_run_min_instances" {
  description = "Minimum number of Cloud Run instances (0 = scale to zero)"
  type        = string
  default     = "0"
}

variable "cloud_run_max_instances" {
  description = "Maximum number of Cloud Run instances"
  type        = string
  default     = "2"
}

variable "keycloak_min_instances" {
  description = "Minimum number of Keycloak instances (1 recommended for warm start)"
  type        = string
  default     = "0"
}

# =============================================================================
# NETWORKING
# =============================================================================

variable "vpc_connector_name" {
  description = "Full name of Serverless VPC Connector (e.g., projects/PROJECT/locations/REGION/connectors/NAME)"
  type        = string
  default     = ""
}

variable "cloud_run_hash" {
  description = "Cloud Run URL hash suffix (auto-generated by GCP)"
  type        = string
  default     = "xxxxx"
}

# =============================================================================
# SERVICE ACCOUNTS
# =============================================================================

variable "mcp_gateway_service_account" {
  description = "Service account email for MCP Gateway"
  type        = string
}

variable "mcp_suite_service_account" {
  description = "Service account email for MCP Suite services"
  type        = string
}

variable "keycloak_service_account" {
  description = "Service account email for Keycloak"
  type        = string
}

# =============================================================================
# SECRETS (Secret Manager References)
# =============================================================================

variable "claude_api_key_secret" {
  description = "Secret Manager secret name for Claude API key"
  type        = string
}

variable "keycloak_admin_user_secret" {
  description = "Secret Manager secret name for Keycloak admin username"
  type        = string
}

variable "keycloak_admin_password_secret" {
  description = "Secret Manager secret name for Keycloak admin password"
  type        = string
}

variable "keycloak_db_password_secret" {
  description = "Secret Manager secret name for Keycloak database password"
  type        = string
}

# =============================================================================
# DATABASE CONFIGURATION
# =============================================================================

variable "postgres_connection_name" {
  description = "Cloud SQL PostgreSQL connection name (PROJECT:REGION:INSTANCE)"
  type        = string
}

variable "keycloak_db_name" {
  description = "Keycloak database name"
  type        = string
  default     = "keycloak"
}

variable "keycloak_db_user" {
  description = "Keycloak database user"
  type        = string
  default     = "keycloak"
}

variable "tamshai_db_name" {
  description = "Tamshai application database name"
  type        = string
  default     = "tamshai"
}

variable "tamshai_db_user" {
  description = "Tamshai database user"
  type        = string
  default     = "tamshai_app"
}

variable "tamshai_db_password" {
  description = "Tamshai database password"
  type        = string
  sensitive   = true
}

variable "mongodb_uri" {
  description = "MongoDB Atlas connection URI"
  type        = string
  sensitive   = true
}

# =============================================================================
# REDIS CONFIGURATION
# =============================================================================

variable "redis_host" {
  description = "Redis host (Utility VM internal IP for Phase 1)"
  type        = string
}

# =============================================================================
# DOMAIN CONFIGURATION
# =============================================================================

variable "keycloak_domain" {
  description = "Keycloak domain (e.g., auth.tamshai.com)"
  type        = string
}

# =============================================================================
# WEB PORTAL CONFIGURATION
# =============================================================================

variable "enable_web_portal" {
  description = "Enable Web Portal Cloud Run service"
  type        = bool
  default     = true
}

variable "web_portal_service_account" {
  description = "Service account email for Web Portal"
  type        = string
  default     = ""
}
