/**
 * Jest Integration Test Configuration
 *
 * Separate config for integration tests that require running services
 * (PostgreSQL, Redis, etc.)
 *
 * Environment variables are loaded from infrastructure/docker/.env (generated by Terraform)
 * and then derived values are set for test connectivity.
 *
 * Variable Derivation:
 * - POSTGRES_HOST: Always 127.0.0.1 (host-to-container connection)
 * - POSTGRES_PORT: Derived from PORT_POSTGRES
 * - POSTGRES_USER: tamshai_app (RLS-enabled user)
 * - POSTGRES_DB: tamshai_hr (default database)
 * - TAMSHAI_APP_PASSWORD: 'changeme' (matches sample-data/*.sql)
 * - KEYCLOAK_URL: Derived from PORT_KEYCLOAK
 * - MCP_*_URL: Derived from PORT_MCP_* variables
 */

const path = require('path');
const fs = require('fs');

// Load environment variables from .env file (generated by Terraform from GitHub secrets/variables)
// IMPORTANT: Use override: true to ensure .env values take precedence over stale shell env vars
const envPath = path.resolve(__dirname, '../../infrastructure/docker/.env');
if (fs.existsSync(envPath)) {
  require('dotenv').config({ path: envPath, override: true });
}

// =============================================================================
// DERIVE TEST ENVIRONMENT VARIABLES FROM TERRAFORM-GENERATED .env
// =============================================================================

// Database connection (host-to-container via exposed ports)
process.env.POSTGRES_HOST = process.env.POSTGRES_HOST || '127.0.0.1';
process.env.POSTGRES_PORT = process.env.POSTGRES_PORT || process.env.PORT_POSTGRES;
process.env.POSTGRES_DB = process.env.POSTGRES_DB || 'tamshai_hr';
process.env.POSTGRES_USER = process.env.POSTGRES_USER || 'tamshai_app';
process.env.TAMSHAI_APP_PASSWORD = process.env.TAMSHAI_APP_PASSWORD || 'changeme';

// Keycloak URL (for TOTP management in tests)
// Local dev Keycloak uses /auth prefix (KC_HTTP_RELATIVE_PATH=/auth in docker-compose.yml)
// CI Keycloak runs at root path (no /auth) - CI sets KEYCLOAK_URL explicitly
const keycloakPort = process.env.PORT_KEYCLOAK;
process.env.KEYCLOAK_URL = process.env.KEYCLOAK_URL || `http://127.0.0.1:${keycloakPort}/auth`;
process.env.KEYCLOAK_ADMIN_PASSWORD = process.env.KEYCLOAK_ADMIN_PASSWORD || 'admin';

// MCP Service URLs (for integration tests)
const mcpGatewayPort = process.env.PORT_MCP_GATEWAY;
const mcpFinancePort = process.env.PORT_MCP_FINANCE;
const mcpUiPort = process.env.PORT_MCP_UI;
process.env.MCP_GATEWAY_URL = process.env.MCP_GATEWAY_URL || `http://127.0.0.1:${mcpGatewayPort}`;
process.env.MCP_FINANCE_URL = process.env.MCP_FINANCE_URL || `http://127.0.0.1:${mcpFinancePort}`;
process.env.MCP_UI_URL = process.env.MCP_UI_URL || `http://127.0.0.1:${mcpUiPort}`;

// =============================================================================
// VALIDATE REQUIRED SECRETS (must come from GitHub Secrets via Terraform)
// =============================================================================

const REQUIRED_ENV_VARS = ['DEV_USER_PASSWORD', 'TAMSHAI_DB_PASSWORD', 'MCP_INTERNAL_SECRET'];
const missing = REQUIRED_ENV_VARS.filter(v => !process.env[v]);
if (missing.length > 0) {
  console.warn(`\n⚠️  Missing environment variables: ${missing.join(', ')}`);
  console.warn(`   These should be loaded from infrastructure/docker/.env (generated by Terraform)`);
  console.warn(`   Run: cd infrastructure/terraform/dev && terraform apply -var-file=dev.tfvars\n`);
}

module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  maxWorkers: 1, // Run serially to avoid database conflicts
  testMatch: [
    '**/integration/**/*.test.ts',
    '**/integration/**/*.spec.ts',
  ],
  setupFilesAfterEnv: ['<rootDir>/src/__tests__/integration/setup.ts'],
  testTimeout: 30000, // 30 second timeout for database operations
  collectCoverageFrom: [
    'src/**/*.ts',
    '!src/**/*.d.ts',
    '!src/**/*.test.ts',
  ],
  transformIgnorePatterns: [
    'node_modules/(?!(uuid)/)',
  ],
  // Integration tests are slower, disable coverage thresholds
  coverageThreshold: undefined,
};
