# Grype vulnerability scanner configuration
# https://github.com/anchore/grype#configuration

ignore:
  # CVE-2026-22817 and CVE-2026-22818 are fixed in Hono 4.11.4
  # We have 4.11.4 installed via @modelcontextprotocol/sdk
  # The vulnerability databases may not be updated yet to reflect the fix
  # See: https://github.com/honojs/hono/security
  - vulnerability: CVE-2026-22817
    fix-state: fixed
  - vulnerability: CVE-2026-22818
    fix-state: fixed
