# Grype vulnerability scanner configuration
# https://github.com/anchore/grype#configuration

ignore:
  # Hono JWT vulnerabilities - fixed in Hono 4.11.4
  # Installed via @modelcontextprotocol/sdk
  - vulnerability: CVE-2026-22817
  - vulnerability: CVE-2026-22818

  # Alpine base image vulnerabilities - fixes not yet available in Alpine stable
  # Dockerfile has `apk upgrade` to apply patches when released
  # Monitoring: https://security.alpinelinux.org/
  #
  # CVE-2026-22184 (CRITICAL) - zlib vulnerability
  - vulnerability: CVE-2026-22184

  # CVE-2025-60876 (MEDIUM) - busybox vulnerability
  - vulnerability: CVE-2025-60876

  # npm bundled dependencies - npm is NOT used at runtime in production containers
  # We only run `node dist/index.js` - npm is only needed during build phase
  # These packages are in /usr/local/lib/node_modules/npm/node_modules/
  #
  # GHSA-3xgq-45jj-v275 (HIGH) - cross-spawn RegExp DoS
  - vulnerability: GHSA-3xgq-45jj-v275
  #
  # GHSA-5j98-mcp5-4vw2 (HIGH) - glob ReDoS vulnerability
  - vulnerability: GHSA-5j98-mcp5-4vw2
  #
  # GHSA-v6h2-p8h4-qcjw (LOW) - brace-expansion ReDoS
  - vulnerability: GHSA-v6h2-p8h4-qcjw
  #
  # GHSA-73rr-hh4g-fpgx (LOW) - diff ReDoS vulnerability
  - vulnerability: GHSA-73rr-hh4g-fpgx
  #
  # GHSA-8qq5-rm4j-mr97 (HIGH) - tar arbitrary file write vulnerability
  - vulnerability: GHSA-8qq5-rm4j-mr97
  #
  # GHSA-r6q2-hw4h-h46w (HIGH) - tar directory traversal vulnerability
  - vulnerability: GHSA-r6q2-hw4h-h46w
  #
  # GHSA-34x7-hfp2-rc4v (HIGH) - tar arbitrary file overwrite via insufficient symlink protection
  - vulnerability: GHSA-34x7-hfp2-rc4v
