# Grype vulnerability scanner configuration
# https://github.com/anchore/grype#configuration

ignore:
  # Hono JWT vulnerabilities - fixed in Hono 4.11.4
  # Installed via @modelcontextprotocol/sdk
  - vulnerability: CVE-2026-22817
  - vulnerability: CVE-2026-22818

  # Alpine base image vulnerabilities - fixes not yet available in Alpine stable
  # Dockerfile has `apk upgrade` to apply patches when released
  # Monitoring: https://security.alpinelinux.org/
  #
  # CVE-2026-22184 (CRITICAL) - zlib vulnerability
  - vulnerability: CVE-2026-22184

  # CVE-2025-60876 (MEDIUM) - busybox vulnerability
  - vulnerability: CVE-2025-60876
