name: 'Setup SSH'
description: 'Configure SSH key and known hosts for VPS deployment'

inputs:
  ssh-key:
    description: 'SSH private key (Ed25519 PEM format)'
    required: true
  host:
    description: 'Target host IP address'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Setup SSH key
      shell: bash
      run: |
        mkdir -p ~/.ssh
        echo "${{ inputs.ssh-key }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        # Validate key format
        ssh-keygen -y -f ~/.ssh/id_ed25519 > /dev/null 2>&1 || {
          echo "::error::SSH key format is invalid"
          exit 1
        }
        ssh-keyscan -H ${{ inputs.host }} >> ~/.ssh/known_hosts 2>/dev/null || {
          echo "::warning::Could not scan host keys, continuing anyway"
        }
        echo "SSH key configured"
