# Kong Gateway Declarative Configuration - VPS/Staging
# Tamshai Corp Enterprise AI
#
# This configuration is used for VPS deployments where Kong sits behind Caddy.
# Caddy handles TLS termination and routes /api/* to Kong.

_format_version: "3.0"
_transform: true

# =============================================================================
# SERVICES
# =============================================================================
services:
  # MCP Gateway Service
  - name: mcp-gateway-service
    url: http://mcp-gateway:3100
    connect_timeout: 60000
    write_timeout: 60000
    read_timeout: 60000
    retries: 3

# =============================================================================
# ROUTES
# =============================================================================
routes:
  # SSE Query Endpoint (v1.4 - Section 6.1)
  # GET /api/query?q=...&token=... for streaming AI responses
  # POST /api/query with JSON body also supported for Flutter/mobile clients
  - name: sse-query-route
    service: mcp-gateway-service
    paths:
      - /api/query
    methods:
      - GET
      - POST
      - OPTIONS
    strip_path: false
    preserve_host: true

  # AI Query Endpoints (protected) - POST version
  - name: ai-query-route
    service: mcp-gateway-service
    paths:
      - /api/ai
    methods:
      - POST
      - OPTIONS
    strip_path: false
    preserve_host: true

  # Confirmation Endpoint (v1.4 - Section 5.6)
  # POST /api/confirm/:id for human-in-the-loop approvals
  - name: confirm-route
    service: mcp-gateway-service
    paths:
      - ~/api/confirm/.*
    methods:
      - POST
      - OPTIONS
    strip_path: false
    preserve_host: true

  # Health Check (unprotected)
  - name: health-route
    service: mcp-gateway-service
    paths:
      - /api/health
      - /health
    methods:
      - GET
    strip_path: false

  # MCP Tool Proxy Endpoints (protected) - v1.4
  # Matches all /api/mcp/* paths including /api/mcp/tools and /api/mcp/:server/:tool
  - name: mcp-tool-proxy-route
    service: mcp-gateway-service
    paths:
      - ~/api/mcp/.*
    methods:
      - GET
      - POST
      - OPTIONS
    strip_path: false
    preserve_host: true

  # User Info (protected)
  - name: user-info-route
    service: mcp-gateway-service
    paths:
      - /api/user
    methods:
      - GET
    strip_path: false

# =============================================================================
# PLUGINS
# =============================================================================
plugins:
  # CORS - Allow cross-origin requests
  # Defense-in-depth: Explicit origins prevent CORS bypass via Caddy misconfiguration
  - name: cors
    config:
      origins:
        - https://www.tamshai.com
        - https://portal.tamshai.com
        - https://finance.tamshai.com
        - https://sales.tamshai.com
        - https://support.tamshai.com
        - https://hr.tamshai.com
        - https://payroll.tamshai.com
        - https://tax.tamshai.com
        - https://customer-support.tamshai.com
      methods:
        - GET
        - POST
        - OPTIONS
      headers:
        - Accept
        - Authorization
        - Content-Type
        - X-Request-ID
      exposed_headers:
        - X-Request-ID
        - X-RateLimit-Remaining
      credentials: true
      max_age: 3600

  # Rate Limiting - Per user (AI queries are expensive)
  - name: rate-limiting
    route: ai-query-route
    config:
      minute: 60
      hour: 500
      policy: local
      fault_tolerant: true
      hide_client_headers: false
      redis_ssl: false

  # Rate Limiting - SSE queries
  - name: rate-limiting
    route: sse-query-route
    config:
      minute: 60
      hour: 500
      policy: local
      fault_tolerant: true
      hide_client_headers: false

  # Request Size Limiting
  - name: request-size-limiting
    config:
      allowed_payload_size: 10
      size_unit: megabytes

  # Response Transformer - Add security headers
  - name: response-transformer
    config:
      add:
        headers:
          - "X-Content-Type-Options: nosniff"
          - "X-Frame-Options: DENY"
          - "X-XSS-Protection: 1; mode=block"
          - "Referrer-Policy: strict-origin-when-cross-origin"

# =============================================================================
# CONSUMERS (for future API key support)
# =============================================================================
consumers:
  - username: mcp-gateway-internal
    custom_id: mcp-gateway-service-account

# =============================================================================
# UPSTREAMS (for load balancing in production)
# =============================================================================
upstreams:
  - name: mcp-gateway-upstream
    algorithm: round-robin
    healthchecks:
      active:
        healthy:
          interval: 5
          successes: 2
        unhealthy:
          interval: 5
          http_failures: 3
        http_path: /health
        timeout: 3
      passive:
        healthy:
          successes: 2
        unhealthy:
          http_failures: 3
    targets:
      - target: mcp-gateway:3100
        weight: 100
