name: 'Setup Keycloak'
description: 'Start Keycloak container for CI testing. Supports realm import (default) or Terraform-managed configuration.'

inputs:
  realm-export-path:
    description: 'Path to realm export JSON file (ignored when import-realm is false)'
    required: false
    default: 'keycloak/realm-export-dev.json'
  keycloak-port:
    description: 'Host port for Keycloak'
    required: true
  keycloak-version:
    description: 'Keycloak version to use'
    required: false
    default: '26.0.7'
  wait-timeout:
    description: 'Maximum wait time in seconds for Keycloak to start'
    required: false
    default: '300'
  import-realm:
    description: 'Whether to import realm from JSON on startup. Set to false when using Terraform.'
    required: false
    default: 'true'
  admin-password:
    description: 'Keycloak admin password'
    required: false
    default: 'admin'
  http-relative-path:
    description: 'HTTP relative path for Keycloak (e.g. /auth). Empty string for no prefix.'
    required: false
    default: '/auth'
  extra-features:
    description: 'Comma-separated Keycloak features to enable (e.g. token-exchange,admin-fine-grained-authz)'
    required: false
    default: ''

outputs:
  keycloak-url:
    description: 'Keycloak base URL'
    value: ${{ steps.start.outputs.keycloak-url }}
  issuer:
    description: 'OIDC issuer URL for tamshai-corp realm'
    value: ${{ steps.start.outputs.issuer }}
  jwks-uri:
    description: 'JWKS URI for token verification'
    value: ${{ steps.start.outputs.jwks-uri }}

runs:
  using: 'composite'
  steps:
    - name: Start Keycloak container
      id: start
      shell: bash
      # Pass passwords via env vars to avoid shell escaping issues with special characters
      # (e.g., passwords containing |, &, ;, ` characters)
      env:
        KC_ADMIN_PASSWORD: ${{ inputs.admin-password }}
        KC_PORT: ${{ inputs.keycloak-port }}
        KC_VERSION: ${{ inputs.keycloak-version }}
        KC_REL_PATH: ${{ inputs.http-relative-path }}
        KC_FEATURES: ${{ inputs.extra-features }}
        KC_IMPORT_REALM: ${{ inputs.import-realm }}
        KC_REALM_EXPORT_PATH: ${{ inputs.realm-export-path }}
        KC_WORKSPACE: ${{ github.workspace }}
      run: |
        # Pull Keycloak image with retry logic (handles intermittent CDN/TLS issues)
        echo "Pulling Keycloak image with retry logic..."
        for i in {1..5}; do
          echo "Attempt $i: Pulling quay.io/keycloak/keycloak:${KC_VERSION}..."
          if docker pull "quay.io/keycloak/keycloak:${KC_VERSION}"; then
            echo "✅ Image pulled successfully"
            break
          fi
          if [ $i -eq 5 ]; then
            echo "❌ Failed to pull image after 5 attempts"
            exit 1
          fi
          echo "Pull failed, waiting $((i * 10)) seconds before retry..."
          sleep $((i * 10))
        done

        # Build docker run command array (avoids eval and shell escaping issues)
        # Set admin credentials for both Keycloak 24 (KEYCLOAK_ADMIN) and 26+ (KC_BOOTSTRAP_ADMIN)
        # pragma: allowlist secret (admin credentials are dev/CI only)
        DOCKER_ARGS=(
          -d
          --name keycloak
          -p "${KC_PORT}:8080"
          -e KEYCLOAK_ADMIN=admin
          -e "KEYCLOAK_ADMIN_PASSWORD=${KC_ADMIN_PASSWORD}"
          -e KC_BOOTSTRAP_ADMIN_USERNAME=admin
          -e "KC_BOOTSTRAP_ADMIN_PASSWORD=${KC_ADMIN_PASSWORD}"
          -e KC_HOSTNAME=localhost
          -e "KC_HOSTNAME_PORT=${KC_PORT}"
        )

        # Set relative path if provided
        if [ -n "$KC_REL_PATH" ]; then
          DOCKER_ARGS+=(-e "KC_HTTP_RELATIVE_PATH=${KC_REL_PATH}")
        fi

        # Build start command args
        START_ARGS=(start-dev --http-port=8080)

        # Add realm import if enabled
        if [ "$KC_IMPORT_REALM" = "true" ]; then
          DOCKER_ARGS+=(-v "${KC_WORKSPACE}/${KC_REALM_EXPORT_PATH}:/opt/keycloak/data/import/realm.json")
          START_ARGS+=(--import-realm)
        fi

        # Add extra features if specified
        if [ -n "$KC_FEATURES" ]; then
          START_ARGS+=("--features=${KC_FEATURES}")
        fi

        # Run Keycloak using array expansion (properly handles special characters)
        docker run "${DOCKER_ARGS[@]}" "quay.io/keycloak/keycloak:${KC_VERSION}" "${START_ARGS[@]}"
        echo "Keycloak container started"

        # Set outputs - build path prefix from relative path
        echo "keycloak-url=http://localhost:${KC_PORT}" >> $GITHUB_OUTPUT
        echo "issuer=http://localhost:${KC_PORT}${KC_REL_PATH}/realms/tamshai-corp" >> $GITHUB_OUTPUT
        echo "jwks-uri=http://localhost:${KC_PORT}${KC_REL_PATH}/realms/tamshai-corp/protocol/openid-connect/certs" >> $GITHUB_OUTPUT

    - name: Wait for Keycloak
      shell: bash
      env:
        KC_PORT: ${{ inputs.keycloak-port }}
        KC_REL_PATH: ${{ inputs.http-relative-path }}
        KC_TIMEOUT: ${{ inputs.wait-timeout }}
      run: |
        echo "Waiting for Keycloak to be ready..."
        ATTEMPTS=$((KC_TIMEOUT / 5))
        for i in $(seq 1 $ATTEMPTS); do
          if curl -sf "http://localhost:${KC_PORT}${KC_REL_PATH}/realms/master" > /dev/null 2>&1; then
            echo "Keycloak is ready after $i attempts"
            sleep 5
            exit 0
          fi
          echo "Attempt $i/$ATTEMPTS: Keycloak not ready yet..."
          sleep 5
        done
        echo "Keycloak failed to start within $KC_TIMEOUT seconds"
        docker logs keycloak
        exit 1

    - name: Verify Keycloak Realm
      shell: bash
      env:
        KC_PORT: ${{ inputs.keycloak-port }}
        KC_REL_PATH: ${{ inputs.http-relative-path }}
        KC_IMPORT_REALM: ${{ inputs.import-realm }}
      run: |
        # Skip realm verification when not importing (Terraform will create it later)
        if [ "$KC_IMPORT_REALM" = "false" ]; then
          echo "Skipping realm verification (import-realm=false, Terraform will configure)"
          exit 0
        fi
        REALM_CHECK=$(curl -sf "http://localhost:${KC_PORT}${KC_REL_PATH}/realms/tamshai-corp/.well-known/openid-configuration" || echo "FAILED")
        if [[ "$REALM_CHECK" == "FAILED" ]]; then
          echo "ERROR: tamshai-corp realm not found"
          docker logs keycloak | tail -50
          exit 1
        fi
        echo "Keycloak realm 'tamshai-corp' is available"
        echo "JWKS URI: $(echo $REALM_CHECK | jq -r '.jwks_uri')"
