# =============================================================================
# Cloud Build: Provision Production Users
# =============================================================================
#
# Loads HR sample data into Cloud SQL and syncs users to Keycloak.
# Runs within GCP network and uses Cloud SQL Proxy for private IP access.
#
# Architecture:
#   - Each step that needs DB access downloads and runs its own Cloud SQL Proxy
#   - Steps are isolated (no shared localhost), so proxy runs per-step
#   - /workspace is shared for scripts and data files
#
# Usage:
#   # Verify only (safe, read-only)
#   gcloud builds submit --config=scripts/gcp/cloudbuild-provision-users.yaml \
#     --substitutions=_ACTION=verify-only .
#
#   # Load HR data + sync users
#   gcloud builds submit --config=scripts/gcp/cloudbuild-provision-users.yaml \
#     --substitutions=_ACTION=all .
#
# Required secrets in Secret Manager:
#   - tamshai-prod-db-password
#   - tamshai-prod-keycloak-admin-password
#   - mcp-hr-service-client-secret
#   - prod-user-password
#
# =============================================================================

substitutions:
  _ACTION: 'verify-only'  # verify-only, load-hr-data, sync-users, all
  _DRY_RUN: 'false'
  _FORCE_PASSWORD_RESET: 'false'
  _REGION: ''  # REQUIRED: Must be provided via --substitutions (no hardcoded default)
  # Issue #32 Fix: Cannot use ${_REGION} in substitution defaults - construct in steps instead
  _KEYCLOAK_URL: 'https://keycloak-fn44nd7wba-uc.a.run.app/auth'
  _KEYCLOAK_REALM: 'tamshai-corp'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_MEDIUM'

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/tamshai-prod-db-password/versions/latest
      env: 'DB_PASSWORD'
    - versionName: projects/$PROJECT_ID/secrets/tamshai-prod-keycloak-admin-password/versions/latest
      env: 'KC_ADMIN_PASSWORD'
    - versionName: projects/$PROJECT_ID/secrets/mcp-hr-service-client-secret/versions/latest
      env: 'KC_CLIENT_SECRET'
    - versionName: projects/$PROJECT_ID/secrets/prod-user-password/versions/latest
      env: 'PROD_USER_PASSWORD'

steps:
  # ===========================================================================
  # Step 0: Display configuration
  # ===========================================================================
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'show-config'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "=============================================="
        echo "Provision Production Users (Cloud Build)"
        echo "=============================================="
        echo "Action:              ${_ACTION}"
        echo "Dry Run:             ${_DRY_RUN}"
        echo "Force Password Reset: ${_FORCE_PASSWORD_RESET}"
        echo "Region:              ${_REGION}"
        echo "Cloud SQL Instance:  ${PROJECT_ID}:${_REGION}:tamshai-prod-postgres"
        echo "Keycloak URL:        ${_KEYCLOAK_URL}"
        echo "=============================================="

  # ===========================================================================
  # Step 1: Verify current state (Cloud SQL + Keycloak)
  # ===========================================================================
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'verify-state'
    entrypoint: 'bash'
    secretEnv: ['DB_PASSWORD', 'KC_ADMIN_PASSWORD']
    env:
      # Issue #32 Fix: Construct CLOUD_SQL_INSTANCE inline (can't use substitution refs in defaults)
      - 'CLOUD_SQL_INSTANCE=${PROJECT_ID}:${_REGION}:tamshai-prod-postgres'
    args:
      - '-c'
      - |
        set -e
        echo "=== Verifying Current State ==="

        # Install PostgreSQL client
        apt-get update -qq && apt-get install -qq -y postgresql-client netcat-openbsd > /dev/null

        # Source the connection helper
        source /workspace/scripts/gcp/lib/cloudsql-connect.sh

        # Start Cloud SQL Proxy
        start_proxy

        # Test database connection and count employees
        echo ""
        echo "[INFO] Testing database connection..."
        if EMPLOYEE_COUNT=$(cloudsql_query "SELECT COUNT(*) FROM hr.employees WHERE UPPER(status) = 'ACTIVE';" 2>/dev/null); then
          echo "[OK] Connected to Cloud SQL"
          echo "[INFO] Active employees: $$EMPLOYEE_COUNT"
          echo "employee_count=$$EMPLOYEE_COUNT" > /workspace/verify-state.env

          # Show sample employees
          echo ""
          echo "=== Sample Employees ==="
          cloudsql_exec "SELECT id, first_name, last_name, email, department FROM hr.employees LIMIT 5;" || true
        else
          echo "[WARN] Could not connect to database or table doesn't exist"
          echo "employee_count=0" > /workspace/verify-state.env
        fi

        # Stop proxy before Keycloak check (cleanup)
        stop_proxy

        # Check Keycloak
        echo ""
        echo "[INFO] Checking Keycloak..."
        KC_TOKEN=$(curl -sf -X POST "${_KEYCLOAK_URL}/realms/master/protocol/openid-connect/token" \
          -H "Content-Type: application/x-www-form-urlencoded" \
          -d "username=admin" \
          -d "password=$$KC_ADMIN_PASSWORD" \
          -d "grant_type=password" \
          -d "client_id=admin-cli" 2>/dev/null | grep -o '"access_token":"[^"]*"' | cut -d'"' -f4 || echo "")

        if [ -z "$$KC_TOKEN" ]; then
          echo "[WARN] Could not get Keycloak admin token"
          echo "keycloak_users=unknown" >> /workspace/verify-state.env
        else
          echo "[OK] Keycloak authentication successful"
          USER_COUNT=$(curl -sf "${_KEYCLOAK_URL}/admin/realms/${_KEYCLOAK_REALM}/users?max=1000" \
            -H "Authorization: Bearer $$KC_TOKEN" 2>/dev/null | grep -o '"username"' | wc -l || echo "0")
          echo "[INFO] Keycloak users in ${_KEYCLOAK_REALM}: $$USER_COUNT"
          echo "keycloak_users=$$USER_COUNT" >> /workspace/verify-state.env
        fi

        echo ""
        echo "=== State Summary ==="
        cat /workspace/verify-state.env
    waitFor: ['show-config']

  # ===========================================================================
  # Step 2: Load HR sample data (conditional)
  # ===========================================================================
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'load-hr-data'
    entrypoint: 'bash'
    secretEnv: ['DB_PASSWORD']
    env:
      # Issue #32 Fix: Construct CLOUD_SQL_INSTANCE inline
      - 'CLOUD_SQL_INSTANCE=${PROJECT_ID}:${_REGION}:tamshai-prod-postgres'
    args:
      - '-c'
      - |
        set -e

        # Check if we should load data
        if [ "${_ACTION}" != "load-hr-data" ] && [ "${_ACTION}" != "all" ]; then
          echo "[SKIP] Action is ${_ACTION}, skipping HR data load"
          exit 0
        fi

        echo "=== Loading HR Sample Data ==="

        if [ "${_DRY_RUN}" = "true" ]; then
          echo "[DRY RUN] Would load sample-data/hr-data.sql"
          echo "File size: $(wc -l < /workspace/sample-data/hr-data.sql) lines"
          exit 0
        fi

        # Install PostgreSQL client
        apt-get update -qq && apt-get install -qq -y postgresql-client netcat-openbsd > /dev/null

        # Source the connection helper
        source /workspace/scripts/gcp/lib/cloudsql-connect.sh

        # Start Cloud SQL Proxy
        start_proxy

        # Load the data
        echo "[INFO] Loading HR data from sample-data/hr-data.sql..."
        cloudsql_exec_file /workspace/sample-data/hr-data.sql

        # Verify
        EMPLOYEE_COUNT=$(cloudsql_query "SELECT COUNT(*) FROM hr.employees WHERE UPPER(status) = 'ACTIVE';")
        echo "[OK] HR data loaded: $$EMPLOYEE_COUNT active employees"
    waitFor: ['verify-state']

  # ===========================================================================
  # Step 3: Sync users to Keycloak (conditional)
  # ===========================================================================
  - name: 'node:20-bookworm'
    id: 'sync-users'
    entrypoint: 'bash'
    secretEnv: ['DB_PASSWORD', 'KC_CLIENT_SECRET', 'PROD_USER_PASSWORD']
    env:
      # Issue #32 Fix: Construct CLOUD_SQL_INSTANCE inline
      - 'CLOUD_SQL_INSTANCE=${PROJECT_ID}:${_REGION}:tamshai-prod-postgres'
    args:
      - '-c'
      - |
        set -e

        # Check if we should sync users
        if [ "${_ACTION}" != "sync-users" ] && [ "${_ACTION}" != "all" ]; then
          echo "[SKIP] Action is ${_ACTION}, skipping user sync"
          exit 0
        fi

        echo "=== Syncing Users to Keycloak ==="

        if [ "${_DRY_RUN}" = "true" ]; then
          echo "[DRY RUN] Would run identity-sync"
          echo "  KEYCLOAK_URL: ${_KEYCLOAK_URL}"
          echo "  KEYCLOAK_REALM: ${_KEYCLOAK_REALM}"
          echo "  Force Password Reset: ${_FORCE_PASSWORD_RESET}"
          exit 0
        fi

        # Install netcat for connection helper
        apt-get update -qq && apt-get install -qq -y netcat-openbsd > /dev/null

        # Source the connection helper and start proxy
        source /workspace/scripts/gcp/lib/cloudsql-connect.sh
        start_proxy

        # Install mcp-hr dependencies
        cd /workspace/services/mcp-hr
        npm ci --production=false --silent

        # Build sync arguments
        SYNC_ARGS=""
        if [ "${_FORCE_PASSWORD_RESET}" = "true" ]; then
          SYNC_ARGS="--force-password-reset"
        fi

        # Set environment for identity-sync
        export POSTGRES_HOST=localhost
        export POSTGRES_PORT=5432
        export POSTGRES_DB=tamshai_hr
        export POSTGRES_USER=tamshai
        export POSTGRES_PASSWORD="$$DB_PASSWORD"
        export KEYCLOAK_URL="${_KEYCLOAK_URL}"
        export KEYCLOAK_REALM="${_KEYCLOAK_REALM}"
        export KEYCLOAK_CLIENT_ID=mcp-hr-service
        export KEYCLOAK_CLIENT_SECRET="$$KC_CLIENT_SECRET"
        export DEFAULT_USER_PASSWORD="$$PROD_USER_PASSWORD"
        export ENVIRONMENT=prod

        # Note: identity-sync may require Redis for BullMQ
        # If it fails, we may need to add Redis or make it optional
        echo "[INFO] Running identity-sync..."
        npx tsx src/scripts/sync-identities.ts $$SYNC_ARGS || {
          echo "[ERROR] Identity sync failed"
          echo "[HINT] Check if Redis is required. May need to make BullMQ optional."
          exit 1
        }

        echo "[OK] User sync completed"
    waitFor: ['load-hr-data']

  # ===========================================================================
  # Step 4: Final verification
  # ===========================================================================
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'final-verify'
    entrypoint: 'bash'
    secretEnv: ['DB_PASSWORD', 'KC_ADMIN_PASSWORD']
    env:
      # Issue #32 Fix: Construct CLOUD_SQL_INSTANCE inline
      - 'CLOUD_SQL_INSTANCE=${PROJECT_ID}:${_REGION}:tamshai-prod-postgres'
    args:
      - '-c'
      - |
        set -e
        echo "=== Final Verification ==="

        # Install PostgreSQL client
        apt-get update -qq && apt-get install -qq -y postgresql-client netcat-openbsd > /dev/null

        # Source the connection helper
        source /workspace/scripts/gcp/lib/cloudsql-connect.sh

        # Start Cloud SQL Proxy
        start_proxy

        # Count employees
        EMPLOYEE_COUNT=$(cloudsql_query "SELECT COUNT(*) FROM hr.employees WHERE UPPER(status) = 'ACTIVE';" 2>/dev/null || echo "0")
        SYNCED_COUNT=$(cloudsql_query "SELECT COUNT(*) FROM hr.employees WHERE keycloak_user_id IS NOT NULL;" 2>/dev/null || echo "0")

        # Stop proxy before Keycloak check
        stop_proxy

        # Count Keycloak users
        KC_TOKEN=$(curl -sf -X POST "${_KEYCLOAK_URL}/realms/master/protocol/openid-connect/token" \
          -H "Content-Type: application/x-www-form-urlencoded" \
          -d "username=admin" \
          -d "password=$$KC_ADMIN_PASSWORD" \
          -d "grant_type=password" \
          -d "client_id=admin-cli" 2>/dev/null | grep -o '"access_token":"[^"]*"' | cut -d'"' -f4 || echo "")

        if [ -n "$$KC_TOKEN" ]; then
          KC_USER_COUNT=$(curl -sf "${_KEYCLOAK_URL}/admin/realms/${_KEYCLOAK_REALM}/users?max=1000" \
            -H "Authorization: Bearer $$KC_TOKEN" 2>/dev/null | grep -o '"username"' | wc -l || echo "unknown")
        else
          KC_USER_COUNT="unknown"
        fi

        # Load initial state for comparison
        source /workspace/verify-state.env 2>/dev/null || true

        echo ""
        echo "=============================================="
        echo "PROVISIONING SUMMARY"
        echo "=============================================="
        echo "Action:              ${_ACTION}"
        echo "Dry Run:             ${_DRY_RUN}"
        echo ""
        echo "BEFORE:"
        echo "  HR Employees:      ${employee_count:-unknown}"
        echo "  Keycloak Users:    ${keycloak_users:-unknown}"
        echo ""
        echo "AFTER:"
        echo "  HR Employees:      $$EMPLOYEE_COUNT"
        echo "  Synced to KC:      $$SYNCED_COUNT"
        echo "  Keycloak Users:    $$KC_USER_COUNT"
        echo "=============================================="
    waitFor: ['sync-users']

timeout: '1200s'  # 20 minutes max
