// AutolinkedNativeModules.g.cpp contents generated by "npx @react-native-community/cli autolink-windows"
// This file was manually modified to remove incompatible native modules for RN Windows 0.80 Composition
#include "pch.h"
#include "AutolinkedNativeModules.g.h"

// Note: @react-native-async-storage/async-storage removed - not compatible with RN Windows 0.80 Composition
// Windows auth uses in-memory storage fallback which works correctly

namespace winrt::Microsoft::ReactNative
{

void RegisterAutolinkedNativeModulePackages(winrt::Windows::Foundation::Collections::IVector<winrt::Microsoft::ReactNative::IReactPackageProvider> const& packageProviders)
{
    // No autolinked native modules - all removed modules were incompatible with RN Windows 0.80 Composition
    (void)packageProviders; // Suppress unused parameter warning
}

}
